services:
    # Enables autowiring and autoconfiguration for classes in the App\Controller namespace
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true
        public: true
    App\Controller\UploadController:
        public: true
        autowire: true
        autoconfigure: true
    App\Repository\UserRepository:
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']
    App\MessageHandler\SendEmailMessageHandler:
        tags: ['messenger.message_handler']
        arguments:
            $mailer: '@mailer.mailer'  # Assuming you're using Symfony Mailer
            $logger: '@logger'          # Injecting the logger service
    
parameters:
        database_host: '127.0.0.1'
        database_port: '3306'
        database_user: 'root'
        database_name: 'user_data_management'
